<div class="table-responsive">
  <table class="table table-sm table-bordered table-hover"  width="100%" cellspacing="0" id="books-table">
    <thead>
      <tr>
        <th>Acci&oacute;n</th>
        <th>Código</th>
        <th>Titulo</th>
        <th>Editor</th>
        <th>FechaPub</th>
        <th>PrecioMin</th>
        <th>Precio</th>
        <th>Valoración</th>
        <th>Descripción</th>
        <th>Autores</th>
        <th>Responsable</th>
        <th>Estatus</th>
      </tr>
    </thead>
    <tbody>

    </tbody>
    <tfoot>
      <tr>
        <th>Acci&oacute;n</th>
        <th>Código</th>
        <th>Titulo</th>
        <th>Editor</th>
        <th>FechaPub</th>
        <th>PrecioMin</th>
        <th>Precio</th>
        <th>Valoración</th>
        <th>Descripción</th>
        <th>Autores</th>
        <th>Responsable</th>
        <th>Estatus</th>
      </tr>
    </tfoot>
  </table>
</div>
